site_name: Alarm5854

nav:
- Home: 
  - index.md
  - 学期总结: summary/index.md
- 数理基础课程:
  - mathphys/index.md
  - 数学分析（甲）Ⅰ（H）: 
    - mathphys/math_analysis1/index.md
    - 历年期末卷: mathphys/math_analysis1/exam/index.md
    - 历年小测: mathphys/math_analysis1/quiz/index.md
  - 数学分析（甲）Ⅱ（H）: 
    - mathphys/math_analysis2/index.md
    - 历年期末卷: mathphys/math_analysis2/exam/index.md
    - 历年小测: mathphys/math_analysis2/quiz/index.md
  - 线性代数Ⅰ（H）: 
    - mathphys/linear_algebra1/index.md
    - 历年期末卷: mathphys/linear_algebra1/exam/index.md
    - 历年期中卷/小测: mathphys/linear_algebra1/mid/index.md
  - 线性代数Ⅱ（H）: 
    - mathphys/linear_algebra2/index.md
    - 历年期末卷: mathphys/linear_algebra2/exam/index.md
    - 历年期中卷/小测: mathphys/linear_algebra2/mid/index.md
  - 普通化学（H）: 
    - mathphys/general_chemistry/index.md
    - 历年期末卷: mathphys/general_chemistry/exam/index.md
    - 章节测试: mathphys/general_chemistry/quiz/index.md
  - 普通化学实验（乙）: 
    - mathphys/chemistry_lab/index.md
    - 实验报告: mathphys/chemistry_lab/reports/index.md
    - 历年期末卷: mathphys/chemistry_lab/exam/index.md
  - 普通物理学Ⅰ（H）: 
    - mathphys/general_physics1/index.md
    - 历年期末卷: mathphys/general_physics1/exam/index.md
    - 历年期中卷: mathphys/general_physics1/mid/index.md
  - 普通物理学实验Ⅰ: 
    - mathphys/physics_lab1/index.md
    - 实验报告: mathphys/physics_lab1/reports/index.md
  - 离散数学: 
    - mathphys/discrete_math/index.md
    - 历年期末卷: mathphys/discrete_math/exam/index.md
- 计算机类课程:
  - computer_science/index.md
  - 程序设计与算法基础: computer_science/programming/index.md
  - 数据结构基础: 
    - computer_science/FDS/index.md
    - 历年期末卷: computer_science/FDS/exam/index.md
  - 数字逻辑设计: 
    - computer_science/DD/index.md
    - 实验报告: computer_science/DD/reports/index.md
    - 历年期末卷: computer_science/DD/exam/index.md
  - 高级数据结构与算法分析: 
    - computer_science/ADS/index.md
    - 课程笔记:
      - computer_science/ADS/lecture/index.md
      - AVL 与 Splay: computer_science/ADS/lecture/AVL_Splay/index.md
      - 红黑树与 B+ 树: computer_science/ADS/lecture/RBtree_Bplus/index.md
      - 倒排索引: computer_science/ADS/lecture/InvInd/index.md
      - 左偏堆与斜堆: computer_science/ADS/lecture/Leftist_Skew/index.md
      - 二项队列: computer_science/ADS/lecture/Binomial/index.md
      - 回溯: computer_science/ADS/lecture/Backtrack/index.md
      - 分治: computer_science/ADS/lecture/DivideConquer/index.md
- 思政类课程:
  - political/index.md
  - 思想道德与法治: 
    - political/moral/index.md
    - 复习资料: political/moral/review/index.md
  - 中国近现代史纲要（H）: 
    - political/modern_history/index.md
    - 复习资料: political/modern_history/review/index.md
  - 军事理论: 
    - political/military_theory/index.md
    - 复习资料: political/military_theory/review/index.md
  - 社会主义发展史: political/socialism_history/index.md
  - 形势与政策Ⅰ: 
    - political/situation1/index.md
    - 复习资料: political/situation1/review/index.md
- 体育课程:
  - PE/index.md
  - 军训: PE/military_training/index.md
  - 游泳（初级）: PE/swim1/index.md
  - 无线电测向（初级）: PE/radio1/index.md
- 通识选修课程:
  - general/index.md
  - 百万立方未来世界: general/milcubes/index.md
  - 心理学及应用: general/psy_app/index.md
  - 经济法理论与实务: 
    - general/eco_law/index.md
    - 复习资料: general/eco_law/review/index.md
  - 博弈论基础: general/game_theory/index.md
  - 心理卫生: 
    - general/psy_health/index.md
    - 复习资料: general/psy_health/review/index.md
- 混合特色课程:
  - SHow_for_mIxTure/index.md
  - 混合学习研讨班Ⅰ: SHow_for_mIxTure/discuss1/index.md
  - 混合学习研讨班Ⅱ: SHow_for_mIxTure/discuss2/index.md


theme:
  name: material

  icon:
    logo: material/github

  language: zh

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: 切换到暗色模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: 切换到亮色模式

  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections、

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - admonition
    - def_list
    - footnotes
    - abbr
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - pymdownx.arithmatex:
          generic: true
    - toc:
          permalink: true
          toc_depth: 3
    - pymdownx.highlight:
          anchor_linenums: true
          linenums: true
          use_pygments: true
          pygments_lang_class: true
          linenums_style: pymdownx-inline
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.keys
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.tasklist:
          custom_checkbox: true
    - attr_list
    - pymdownx.emoji
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - meta
    - tables
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - mask
  
extra_css:
  - assets/masked.css
# copyright: Copyright © Alarm5854
